### ISSUE TITLE
Non-anonymous endCallback functions fire at the start

### ISSUE THREAD

**Issue by slaughtr** [nathan818fr/async-loop#2]
As the title states, if you try calling a declared function as the 'endCallback', it fires before anything else happens. I may be misunderstanding some intricacies of JavaScript or I may have become a bit lost in the documentation, but it doesn't seem like it should work like this.

Example:

```javascript
let asyncloop = require('node-async-loop');

asyncloop([1,2,3,4], function(number, next) {

setTimeout(function() {
    console.log(number)
    next()
}, 1000)


}, function() {
    console.log('done')
})
```

 logs: 1, 2, 3, 4, done

```javascript
let asyncloop = require('node-async-loop');

let thingAtEnd = function() {console.log('done')}

asyncloop([1,2,3,4], function(number, next) {

setTimeout(function() {
    console.log(number)
    next()
}, 1000)
}, thingAtEnd())
```

logs: done, 1, 2, 3, 4

**Comment by nathan818fr** [comment]
You need to pass the function reference: `thingAtEnd` and not `thingAtEnd()`.

So the complete correct code is:
```javascript
let asyncloop = require('node-async-loop');

let thingAtEnd = function() {
    console.log('done');
}

asyncloop([1, 2, 3, 4], function(number, next) {
    setTimeout(function() {
        console.log(number);
        next();
    }, 1000);
}, thingAtEnd);
```
logs: 1, 2, 3, 4, done

**Comment by slaughtr** [comment]
Wow that was a fast reply.

Right you are, though I swear I tried that...

This might not be the right place to ask this, but why exactly is that? I understand the difference between using parenthesis and not when assigning, but not when calling...
