### ISSUE TITLE
Not work properly with empty array

### ISSUE THREAD

**Issue by imvikaskohli** [nathan818fr/async-loop#3]
```
let emptyCheck = [];
console.log(emptyCheck.length);
asyncLoop(emptyCheck, function(singleCheck, next){
  console.log("Start",singleCheck);
  next();
}, function(err){
  console.log("Finished");
});
```

// Output:-
0
Start undefined
Start undefined
Finished

But Expected Output:-

0
Finished

**Comment by nathan818fr** [comment]
Thank you for the report.
Unfortunately I do not have time to maintain this project and it is not really useful anymore (since async / await in nodejs 8). I will indicate it on the README.
