### ISSUE TITLE
Error: Handle already running!

### ISSUE THREAD

**Issue by austinmccalley** [nathan818fr/async-loop#4]
Is there a way I can run two cURL get and post requests at the same time. When you currently do it throws an error saying, `Error: Handle already running!`

Here is the full error;
```
Error: Handle already running!
    at Curl.perform (/Users/admin/Desktop/projects/discordBots/Bot/node_modules/node-libcurl/lib/Curl.js:1081:15)
    at Promise (/Users/admin/Desktop/projects/discordBots/Bot/node_modules/curl-request/index.js:169:27)
    at Promise (<anonymous>)
    at module.exports._submit (/Users/admin/Desktop/projects/discordBots/Bot/node_modules/curl-request/index.js:141:16)
    at module.exports.get (/Users/admin/Desktop/projects/discordBots/Bot/node_modules/curl-request/index.js:87:21)
    at getHomework (/Users/admin/Desktop/projects/discordBots/Bot/index.js:60:8)
    at Client.client.on (/Users/admin/Desktop/projects/discordBots/Bot/index.js:51:13)
    at emitOne (events.js:115:13)
    at Client.emit (events.js:210:7)
    at MessageCreateHandler.handle (/Users/admin/Desktop/projects/discordBots/Bot/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
```

Is there a way around this or an option to change this in the future?

**Comment by nathan818fr** [comment]
The problem does not come from this library. 
This is a cURL restriction that prevents the same handle from being used concurrently at the same time. Simply create several handles.

**Comment by wahyuandi840** [comment]
hello,
i have same error.
my code is 
/**
 * Triggered from a change to a Cloud Storage bucket.
 *
 * @param {!Object} event Event payload and metadata.
 * @param {!Function} callback Callback function to signal completion.
 */
const storage = require("@google-cloud/storage")();
const curl = new(require('curl-request'))();

exports.getEmail = (event, callback) => {
 const file = event.data;
 const eventAge = Date.now() - Date.parse(event.timestamp);
 const eventMaxAge = 10000;
 
 // Ignore events that are too old
  if (eventAge > eventMaxAge) {
    console.log(`Dropping event ${event} with age ${eventAge} ms.`);
    callback();
    return;
  }


 //console.log(`  Event: ${event.eventId}`);
 //console.log(`  Event Type: ${event.eventType}`);
 //console.log(`  Bucket: ${file.bucket}`);
// console.log(`  File: ${file.name}`);
 //console.log(`  Metageneration: ${file.metageneration}`);
 //console.log(`  Created: ${file.timeCreated}`);
 //console.log(`  Updated: ${file.updated}`);
  
if (file.name.match('registerfolder/') || file.name.match('affiliatefolder/') || file.name.match('orderfolder/') || file.name.match('transactionfolder/') || file.name.match('forgottenfolder/')) {
 	storage.
     bucket(file.bucket).
     file(file.name).
     download(function(err, contents) {
      let obj = JSON.parse(contents.toString());

      curl
       .setBody({
        'from' : obj.from,
        'fromName': obj.sender,
        'apikey': process.env.API_KEY,
        'subject': obj.subject,
        'to': obj.to,
        'bodyHtml': obj.text,
        'isTransactional': true
       })
       .post(process.env.API_URL + 'email/send')
       .then(({
        statusCode,
        body,
        headers
       }) => {
        console.log(statusCode, body, headers)
       })
       .catch((e) => {
        console.log(e);
       });

     });
}
 
 callback();
};

log error is

Error: Handle already running! at Error (native) at Curl.perform (/user_code/node_modules/curl-request/node_modules/node-libcurl/lib/Curl.js:1051:11) at e (/user_code/node_modules/curl-request/index.js:169:27) at _submit (/user_code/node_modules/curl-request/index.js:141:16) at post (/user_code/node_modules/curl-request/index.js:93:21) at /user_code/index.js:48:9 at f (/user_code/node_modules/@google-cloud/storage/node_modules/once/once.js:25:25) at ConcatStream.<anonymous> (/user_code/node_modules/@google-cloud/storage/node_modules/concat-stream/index.js:37:43) at emitNone (events.js:91:20) at ConcatStream.emit (events.js:185:7)
